baseURL = ""
languageCode = "de-de"
title = "Seebrücke Ismaning"
theme = "cayman-hugo-theme"
publishDir = "docs"

[params]
  project_name = "Seebrücke Ismaning"
  project_tagline = "Wir bauen eine Brücke zu sicheren Häfen."

  header_background_color = "#f55511"

  section_headings_color = "#242830"
  body_text_color = "#242830"
  body_link_color = "#f55511"

  footer = "2021 Seebrücke Ismaning | ismaning@seebruecke.org"

[menu]
  [[menu.nav]]
    name = "Aktuelles"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Unsere Forderungen"
    url = "/demands/"
    weight = 2
  [[menu.nav]]
    name = "Interessante Links"
    url = "/links/"
    weight = 3
  [[menu.nav]]
    name = "Über uns"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "Kontakt"
    url = "/contact/"
    weight = 5
  [[menu.nav]]
    name = "Impressum"
    url = "/impressum/"
    weight = 6
